apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-pre-install-hook"
  annotations:
    "helm.sh/hook": pre-install       # 指定为 pre-install 钩子
    "helm.sh/hook-weight": "-5"       # 权重（数值越小执行越早）
    "helm.sh/hook-delete-policy": hook-succeeded  # 执行成功后删除 Job
spec:
  template:
    spec:
      containers:
      - name: pre-install-message
        image: alpine:3.19
        command: ["/bin/sh", "-c"]
        args:
          - echo "=== Pre-Install Hook ===";
            printenv | grep 'CHART_';
      restartPolicy: Never
  backoffLimit: 0  # 失败后不重试