apiVersion: redis.tencentcloud.crossplane.io/v1alpha1
kind: RedisInstance
metadata:
  name: my-redis-demo
spec:
  forProvider:
    availabilityZone: "ap-hongkong"
    typeId: 8  # 实例类型（8 代表主从版，具体值参考腾讯云文档）
    memSize: 1024  # 内存大小（MB）
    redisShardNum: 1  # 分片数（标准版固定为1）
    redisReplicasNum: 1  # 副本数（标准版为1主1从）
    chargeType: POSTPAID


# CVM instance
# apiVersion: cvm.tencentcloud.crossplane.io/v1alpha1
# kind: Instance
# metadata:
#   name: example-cvm
# spec:
#   forProvider:
#     instanceName: "test-crossplane-cvm"
#     availabilityZone: "ap-hongkong-2"
#     instanceChargeType: "SPOTPAID"
#     imageId: "img-487zeit5"
#     instanceType: "SA5.MEDIUM4"
#     systemDiskType: "CLOUD_BSSD"
#     vpcIdRef:
#       name: "example-cvm-vpc"
#     subnetIdRef:
#       name: "example-cvm-subnet"
